// =============================================================================
// utils/database/db-connection.ts — SECURE DATABASE CONNECTION MANAGER
// =============================================================================
// PURPOSE:
//   Manages secure connections to databases (PostgreSQL, MySQL, SQLite).
//   Supports SSL/TLS encryption, connection pooling, and credential decryption.
//
// WHAT IS A DATABASE CONNECTION?
//   A "connection" is like opening a phone line to the database server.
//   Every time you want to read or write data, you need an open connection.
//   "Connection pooling" means we keep a few connections open and reuse them
//   instead of opening a new one for every query (much faster).
//
// WHAT IS SSL/TLS?
//   SSL (Secure Sockets Layer) / TLS (Transport Layer Security) encrypts
//   the communication between your test and the database server.
//   Without SSL, your data (including passwords!) travels in plain text
//   over the network and could be intercepted. With SSL, it's scrambled.
//
// SUPPORTED DATABASES:
//   🐘 PostgreSQL  → Most popular for enterprise apps
//   🐬 MySQL       → Very common for web apps
//   📄 SQLite      → File-based, no server needed (great for local testing)
//
// HOW TO USE:
//   // Get a connected database client
//   const db = await DbConnection.connect();
//
//   // Run a query
//   const users = await db.query('SELECT * FROM users WHERE email = $1', ['alice@example.com']);
//
//   // Always disconnect when done
//   await db.disconnect();
//
// SETUP IN .env:
//   DB_ENABLED=true
//   DB_TYPE=postgres          ← 'postgres', 'mysql', or 'sqlite'
//   DB_HOST=db.company.com
//   DB_PORT=5432
//   DB_NAME=myapp_test
//   DB_USER=test_user
//   DB_PASSWORD_ENCRYPTED=U2FsdGVkX1...  ← Use npm run encrypt-password to generate
//   DB_SSL=true               ← Enable SSL for production databases
//   DB_SSL_CERT_PATH=./certs/db-ca.pem  ← Path to SSL certificate (optional)
// =============================================================================

import { logger }    from '../helpers/logger';
import { decrypt }   from '../security/crypto-helper';
import * as fs       from 'fs';
import * as path     from 'path';

// =============================================================================
// TYPE DEFINITIONS
// =============================================================================

/**
 * Database type — which database system to connect to.
 */
export type DbType = 'postgres' | 'mysql' | 'sqlite';

/**
 * Configuration for establishing a database connection.
 */
export interface DbConfig {
  /** Which database system: 'postgres', 'mysql', or 'sqlite' */
  type: DbType;

  /** Database server hostname or IP (not needed for SQLite) */
  host?: string;

  /** Database server port (5432 for Postgres, 3306 for MySQL) */
  port?: number;

  /** Database name */
  database: string;

  /** Username (not needed for SQLite) */
  user?: string;

  /**
   * Password in PLAIN TEXT.
   * ⚠️ Prefer using passwordEncrypted + a secret key instead.
   * Only use this for local/dev databases — NEVER production.
   */
  password?: string;

  /**
   * ENCRYPTED password string (generated by the crypto-helper utility).
   * This is the RECOMMENDED way — passwords are never in plain text in .env.
   * To generate: npm run encrypt-password
   */
  passwordEncrypted?: string;

  /** Whether to use SSL/TLS encryption for the connection (default: false) */
  ssl?: boolean;

  /** Path to SSL certificate file (optional, for self-signed certs) */
  sslCertPath?: string;

  /** Maximum number of connections to keep open (default: 5) */
  poolSize?: number;

  /** SQLite: path to the database file (only for type='sqlite') */
  filePath?: string;
}

/**
 * Result from a query — an array of row objects.
 * Each row is a key-value object where keys are column names.
 */
export type QueryResult = Record<string, unknown>[];

// =============================================================================
// CLASS: DbConnection
// =============================================================================
/**
 * A unified database connection that works with PostgreSQL, MySQL, or SQLite.
 *
 * USAGE:
 *   const db = await DbConnection.connect();       // Connect using .env settings
 *   const rows = await db.query('SELECT * FROM users');
 *   const count = await db.execute('UPDATE users SET active = true WHERE id = $1', [42]);
 *   await db.disconnect();
 */
export class DbConnection {
  // Internal reference to the active client (type depends on DB type)
  private client: unknown = null;
  private dbType: DbType;
  private isConnected = false;

  // Make constructor private — use DbConnection.connect() instead
  private constructor(dbType: DbType) {
    this.dbType = dbType;
  }

  // ===========================================================================
  // STATIC FACTORY: connect()
  // ===========================================================================
  /**
   * Creates a DbConnection and establishes the connection.
   * This is the main entry point.
   *
   * EXAMPLE:
   *   const db = await DbConnection.connect();
   *   // Now db is connected and ready to use
   *
   * @param overrideConfig - Optional config override (defaults to .env settings)
   */
  static async connect(overrideConfig?: Partial<DbConfig>): Promise<DbConnection> {
    const cfg = DbConnection.buildConfig(overrideConfig);

    logger.info(`🗄️  Connecting to ${cfg.type.toUpperCase()} database...`);
    logger.info(`   Host: ${cfg.host || 'local file'} | DB: ${cfg.database}`);
    if (cfg.ssl) logger.info(`   🔒 SSL: enabled`);

    const instance = new DbConnection(cfg.type);
    await instance.establishConnection(cfg);
    return instance;
  }

  // ===========================================================================
  // METHOD: query()
  // ===========================================================================
  /**
   * Runs a SELECT query and returns the result rows.
   *
   * Use $1, $2, ... placeholders for parameters (prevents SQL injection!).
   * Never build queries by string concatenation with user input.
   *
   * GOOD ✅:
   *   db.query('SELECT * FROM users WHERE email = $1', ['alice@test.com'])
   *
   * BAD ❌ (SQL injection risk!):
   *   db.query(`SELECT * FROM users WHERE email = '${userInput}'`)
   *
   * @param sql    - SQL query string with $1, $2 placeholders
   * @param params - Values for the placeholders (in order)
   * @returns      Array of row objects
   */
  async query(sql: string, params: unknown[] = []): Promise<QueryResult> {
    this.assertConnected();

    logger.step(`🗄️  DB Query: ${sql.substring(0, 80)}${sql.length > 80 ? '...' : ''}`);

    try {
      if (this.dbType === 'postgres') {
        const { Pool } = await import('pg');
        const pool = this.client as InstanceType<typeof Pool>;
        const result = await pool.query(sql, params);
        logger.info(`   Returned ${result.rows.length} row(s)`);
        return result.rows as QueryResult;

      } else if (this.dbType === 'mysql') {
        // MySQL uses ? placeholders instead of $1, $2
        const mysqlSql = sql.replace(/\$\d+/g, '?');
        return await new Promise((resolve, reject) => {
          (this.client as any).query(mysqlSql, params, (err: Error, rows: QueryResult) => {
            if (err) reject(err);
            else {
              logger.info(`   Returned ${rows.length} row(s)`);
              resolve(rows);
            }
          });
        });

      } else {
        // SQLite placeholder
        logger.warn('SQLite query: install better-sqlite3 and plug it in here.');
        return [];
      }
    } catch (err) {
      logger.error(`❌ DB query failed: ${(err as Error).message}`);
      throw err;
    }
  }

  // ===========================================================================
  // METHOD: execute()
  // ===========================================================================
  /**
   * Runs an INSERT, UPDATE, DELETE, or DDL statement.
   * Returns the number of rows affected.
   *
   * EXAMPLE:
   *   const affected = await db.execute(
   *     'UPDATE users SET last_login = NOW() WHERE id = $1',
   *     [userId]
   *   );
   *   console.log(`${affected} rows updated`);
   */
  async execute(sql: string, params: unknown[] = []): Promise<number> {
    this.assertConnected();

    logger.step(`🗄️  DB Execute: ${sql.substring(0, 80)}${sql.length > 80 ? '...' : ''}`);

    try {
      if (this.dbType === 'postgres') {
        const { Pool } = await import('pg');
        const pool = this.client as InstanceType<typeof Pool>;
        const result = await pool.query(sql, params);
        const count = result.rowCount ?? 0;
        logger.info(`   Affected ${count} row(s)`);
        return count;

      } else if (this.dbType === 'mysql') {
        const mysqlSql = sql.replace(/\$\d+/g, '?');
        return await new Promise((resolve, reject) => {
          (this.client as any).query(mysqlSql, params, (err: Error, result: any) => {
            if (err) reject(err);
            else {
              logger.info(`   Affected ${result.affectedRows} row(s)`);
              resolve(result.affectedRows);
            }
          });
        });

      } else {
        logger.warn('SQLite execute: install better-sqlite3 and plug it in here.');
        return 0;
      }
    } catch (err) {
      logger.error(`❌ DB execute failed: ${(err as Error).message}`);
      throw err;
    }
  }

  // ===========================================================================
  // METHOD: disconnect()
  // ===========================================================================
  /**
   * Closes the database connection.
   * ALWAYS call this when you're done to free up resources.
   *
   * EXAMPLE:
   *   await db.disconnect();
   */
  async disconnect(): Promise<void> {
    if (!this.isConnected || !this.client) return;

    try {
      if (this.dbType === 'postgres') {
        const { Pool } = await import('pg');
        await (this.client as InstanceType<typeof Pool>).end();
      } else if (this.dbType === 'mysql') {
        (this.client as any).end();
      }

      this.isConnected = false;
      logger.info(`🗄️  Database disconnected.`);
    } catch (err) {
      logger.warn(`Could not cleanly disconnect from database: ${(err as Error).message}`);
    }
  }

  // ===========================================================================
  // PRIVATE: establishConnection()
  // ===========================================================================
  private async establishConnection(cfg: DbConfig): Promise<void> {
    // Resolve password: prefer encrypted → plain text → empty
    let password = cfg.password ?? '';
    if (cfg.passwordEncrypted && cfg.passwordEncrypted !== '') {
      try {
        password = decrypt(cfg.passwordEncrypted);
        logger.info(`   🔓 Password decrypted successfully`);
      } catch {
        logger.warn(`   ⚠️  Could not decrypt DB password — trying plain text`);
      }
    }

    // Build SSL options
    let sslOptions: boolean | object = cfg.ssl ?? false;
    if (cfg.ssl && cfg.sslCertPath) {
      const certPath = path.resolve(process.cwd(), cfg.sslCertPath);
      if (fs.existsSync(certPath)) {
        sslOptions = { ca: fs.readFileSync(certPath).toString() };
        logger.info(`   🔒 SSL certificate loaded: ${certPath}`);
      } else {
        logger.warn(`   ⚠️  SSL cert not found at ${certPath} — using system CA`);
      }
    }

    if (cfg.type === 'postgres') {
      const { Pool } = await import('pg');
      this.client = new Pool({
        host:     cfg.host,
        port:     cfg.port,
        database: cfg.database,
        user:     cfg.user,
        password,
        ssl:      sslOptions || undefined,
        max:      cfg.poolSize ?? 5,
        idleTimeoutMillis:    30000,
        connectionTimeoutMillis: 5000,
      });
      // Test the connection
      await (this.client as InstanceType<typeof Pool>).query('SELECT 1');

    } else if (cfg.type === 'mysql') {
      const mysql = await import('mysql2');
      this.client = mysql.createConnection({
        host:     cfg.host,
        port:     cfg.port,
        database: cfg.database,
        user:     cfg.user,
        password,
        ssl:      (typeof sslOptions === 'object')
          ? JSON.stringify(sslOptions)
          : undefined,
      });
      await new Promise<void>((resolve, reject) => {
        (this.client as any).connect((err: Error) => {
          if (err) reject(err);
          else resolve();
        });
      });

    } else {
      logger.warn(`SQLite support: install 'better-sqlite3' and add connection logic here.`);
    }

    this.isConnected = true;
    logger.pass(`✅ Connected to ${cfg.type.toUpperCase()} database: ${cfg.database}`);
  }

  // ===========================================================================
  // PRIVATE: buildConfig()
  // ===========================================================================
  private static buildConfig(override?: Partial<DbConfig>): DbConfig {
    return {
      type:               (process.env['DB_TYPE'] as DbType) ?? 'postgres',
      host:               process.env['DB_HOST']             ?? 'localhost',
      port:               parseInt(process.env['DB_PORT'] ?? '5432', 10),
      database:           process.env['DB_NAME']             ?? '',
      user:               process.env['DB_USER']             ?? '',
      password:           process.env['DB_PASSWORD']         ?? '',
      passwordEncrypted:  process.env['DB_PASSWORD_ENCRYPTED'] ?? '',
      ssl:                (process.env['DB_SSL'] ?? 'false') === 'true',
      sslCertPath:        process.env['DB_SSL_CERT_PATH']    ?? '',
      poolSize:           parseInt(process.env['DB_POOL_SIZE'] ?? '5', 10),
      ...override,
    };
  }

  // ===========================================================================
  // PRIVATE: assertConnected()
  // ===========================================================================
  private assertConnected(): void {
    if (!this.isConnected || !this.client) {
      throw new Error(
        '❌ DbConnection is not connected. Call DbConnection.connect() first.'
      );
    }
  }
}

// =============================================================================
// HELPER: isDbEnabled
// =============================================================================
/**
 * Returns true if the DB is enabled in .env.
 * Use this to guard database code so it skips gracefully if not configured.
 *
 * EXAMPLE:
 *   if (isDbEnabled()) {
 *     const db = await DbConnection.connect();
 *     // ...
 *   }
 */
export function isDbEnabled(): boolean {
  return (process.env['DB_ENABLED'] ?? 'false').toLowerCase() === 'true';
}
